version: '3'

services:
  app:
    image: node:10
    volumes:      
      - .:/app
      - notused:/app/node_modules
    ports:
      - "3000:3000"
      - "8001:8001"
    command:
      bash -c "cd /app && npm i --no-shrinkwrap --no-package-lock && npm start"

volumes:
  notused:
